:toc:
:toclevels: 5

---

= eclipse-plugin-ecpg

An Eclipse plugin that analyzes and parses https://www.postgresql.org/docs/current/ecpg.html[PostgreSQL ECPG] unique syntax written in C source code.

== Features

* Syntax highlighting
* Resolve host variables
* Resolve sqlca without `#include <sqlca.h>` directive
* Source code formatting
* Resolve cursor identifier

== Limitations

Connection string in `+CONNECT+` statements needs to be enclosed in single or double quotes. Host variables can also be used. +
Examples are shown below:

.Examples
[source,c]
----
// Use quotes for connection string
EXEC SQL CONNECT TO "postgres@localhost:5432" USER "postgres" IDENTIFIED BY "postgres";
EXEC SQL CONNECT TO "tcp:postgresql://localhost/postgres" AS myconnection USER "postgres" IDENTIFIED BY "postgres";
// Or use host variables
EXEC SQL BEGIN DECLARE SECTION;
  const char *target = "postgres@localhost:5432";
  const char *user = "postgres";
  const char *passwd = "postgres";
EXEC SQL END DECLARE SECTION;
EXEC SQL CONNECT TO :target USER :user USING :passwd;
----

== Getting Started

=== Prerequisites

* Eclipse CDT (2023.3~)

TIP: Older cdt versions may work, although not tested.

=== Installation

Put ```plugin.ecpg-x.x.x.YYYYMMDDhhmm.jar``` and ```plugin.common-x.x.x.YYYYMMDDhhmm.jar``` to Eclipseplugins directory (ex.~/eclipse/plugins) and start Eclipse.

TIP: ```plugin.common-x.x.x.YYYYMMDDhhmm.jar``` can be downloaded from https://github.com/hamneko/eclipse-plugin-common/releases[this repository].

=== Change Language Mappings

From eclipse menu bar, select [Window]-[Preferences...]. Under `C/C++` select `Language Mappings`, add following settings and click [Apply and Close].

.Language Mappings
[options="header"]
|===
|Content Type|Language
|C Header File|ECPG
|C Source File|ECPG
|===

TIP: If you have custom file extension for ECPG file (ex. xxx.ecpg), add File Types.

=== Change Formatter

From eclipse menu bar, select [Window]-[Preferences...]. Under `C/C++` - `Code Style` select `Formatter`, change Code Formatter from [built-in] to ECPG and click [Apply and Close].

== Building from Source

Clone the repository:

[source,sh]
----
$ git clone https://github.com/hamneko/eclipse-plugin-ecpg.git
----

Execute following command in cloned directory:

[source,sh]
----
$ ./mvnw clean install
----
